# Embeddings related config
EMBEDDINGS:
  HF_MODEL:
    EMBEDDINGS: sentence-transformers/all-MiniLM-L6-v2

# MongoDB Related Config
MONGODB:
  DB_NAME: K12bot

# Pinecone related Config
PINECONE_DB:
  INDEX_NAME: K12bot