# Embeddings related config
EMBEDDINGS:
  HF_MODEL:
    EMBEDDINGS: sentence-transformers/all-MiniLM-L6-v2

# MongoDB Related Config
MONGODB: 
  DB_NAME: k12chatbot

# Pinecone related Config
PINECONE_DB:
  INDEX_NAME: k12test